CREATE TABLE ROLE (
    ID VARCHAR2(30 BYTE) NOT NULL ENABLE,
	NAME VARCHAR2(45 BYTE),
    PRIMARY KEY (ID)
);

INSERT INTO ROLE VALUES ('1','ROLE_USER');


CREATE TABLE USERS(
  ID VARCHAR2(30 BYTE) NOT NULL ENABLE,
  USERNAME VARCHAR2(255 BYTE),
  password VARCHAR2(255 BYTE),
  PRIMARY KEY (ID)
);



CREATE SEQUENCE  HIBERNATE_SEQUENCE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


CREATE TABLE user_role (
  user_id VARCHAR2(30 BYTE) NOT NULL,
  role_id VARCHAR2(30 BYTE) NOT NULL,
  PRIMARY KEY (user_id,role_id),
 CONSTRAINT fk_user_role_roleid FOREIGN KEY (role_id) REFERENCES ROLE(ID),
CONSTRAINT fk_user_role_userid FOREIGN KEY (user_id) REFERENCES USERS(ID)
);